# NumPy exercises

In [4]:
#import the Numpy package
import numpy as np

In [2]:
#Set the random seed
np.random.seed(859)

In [20]:
#Create a random array of 100 values between 0 and 1
arr_1 = np.random.rand(100)


#Display the resulting array
arr_1

array([0.42255815, 0.7546315 , 0.15434521, 0.195563  , 0.52923742,
       0.84563264, 0.53692927, 0.10062973, 0.17584931, 0.06455847,
       0.95251862, 0.14251995, 0.93253472, 0.80490506, 0.82987014,
       0.10734579, 0.99606908, 0.36307366, 0.97357366, 0.19954192,
       0.65332959, 0.03989576, 0.0289763 , 0.74613546, 0.57462236,
       0.63132034, 0.59196145, 0.60562991, 0.13409761, 0.56283536,
       0.44158393, 0.09517148, 0.6107137 , 0.9190369 , 0.59496618,
       0.31000755, 0.91762925, 0.71088969, 0.19820365, 0.50995713,
       0.46033303, 0.72765561, 0.04195285, 0.5069119 , 0.80199131,
       0.69471662, 0.75764885, 0.84595129, 0.00559662, 0.75116737,
       0.55499287, 0.78714963, 0.58613351, 0.10853481, 0.31684168,
       0.73260784, 0.99017394, 0.73599129, 0.37443579, 0.46714602,
       0.81649109, 0.08249166, 0.72555453, 0.41203892, 0.79413369,
       0.50689104, 0.29080898, 0.45357081, 0.35215014, 0.01848881,
       0.96967125, 0.09692503, 0.16791844, 0.56437997, 0.17589

In [14]:
#Report the shape of the resulting array
arr_1.shape

(100,)

In [15]:
#Report the data type of the resulting array
arr_1.dtype

dtype('float64')

In [17]:
#Remote the mean value of all values in your array
arr_1.mean()

0.4634853558185105

In [21]:
#Multiply each value in your array to get values between 0 and 100, saving the results as "arr_2"
arr_2 = arr_1 * 100

In [23]:
#Reshape the array above to be 25 rows and 4 columns, saving the result as "arr_3"
arr_3 = arr_2.reshape(25,4)


array([[42.25581547, 75.46314971, 15.43452085, 19.55630041],
       [52.92374206, 84.56326385, 53.69292726, 10.06297259],
       [17.58493111,  6.45584678, 95.25186216, 14.25199497],
       [93.25347205, 80.49050609, 82.98701354, 10.73457919],
       [99.60690769, 36.30736571, 97.35736635, 19.95419229],
       [65.33295886,  3.98957647,  2.89763006, 74.61354565],
       [57.46223577, 63.13203435, 59.19614494, 60.562991  ],
       [13.40976149, 56.28353628, 44.15839297,  9.51714817],
       [61.07136967, 91.90368976, 59.49661764, 31.00075489],
       [91.76292457, 71.0889693 , 19.82036506, 50.99571347],
       [46.03330281, 72.76556135,  4.19528503, 50.69119047],
       [80.19913103, 69.47166223, 75.76488461, 84.59512893],
       [ 0.55966208, 75.11673711, 55.4992871 , 78.71496337],
       [58.61335055, 10.85348129, 31.68416839, 73.26078399],
       [99.01739372, 73.59912924, 37.44357912, 46.71460196],
       [81.64910938,  8.24916556, 72.55545258, 41.20389159],
       [79.41336946, 50.

In [24]:
#Show the 3rd row of this array
arr_3[3]

array([93.25347205, 80.49050609, 82.98701354, 10.73457919])

In [25]:
#Show the values in the 2nd column of this array
arr_3[2]

array([17.58493111,  6.45584678, 95.25186216, 14.25199497])

In [26]:
#Show the mean of the values in the 2nd column
arr_3[2].ndarray.mean

<function ndarray.mean>